### ISSUE TITLE
Unlock dependencies

### ISSUE THREAD

**Issue by lukeed** [postcss/postcss-url#145]
All dependencies are pinned to exact versions - [including `postcss`](https://github.com/postcss/postcss-url/blob/master/package.json#L29)

This means that anyone using `postcss` + `postcss-url` today will have 2+ copies of PostCSS active in their toolchain.

**Comment by lukeed** [comment]
Realistically, `postcss` should be a `peerDependency` anyway.

This is a common problem throughout the PostCSS plugin ecosystem.

**Comment by aredridel** [comment]
Now that postcss _is_ a peer dependency, this throws a warning; with npm 7, it becomes a hard stop. Making the peer dependency on postcss `^8.1.2` would help immensely.

**Comment by sergcen** [comment]
fixed in [10.1.0](https://github.com/postcss/postcss-url/releases/tag/10.1.0)

**Comment by lukeed** [comment]
No. This is still an issue: https://github.com/postcss/postcss-url/blob/master/package.json#L26-L29

**Comment by realityking** [comment]
With #156 this is now much improved as it uses the `~` operator :)

**Comment by lukeed** [comment]
Improved but not solved. You should still be trusting dependencies' ability to respect semver & only introduce breaking changes in new major versions. 

The changes here collect all patch updates, but still require that you/the maintainers here manually update the minor versions (even if new the features aren't used). Otherwise, this package will still be pulling in old & outdated versions of packages during `npm install` when the rest of the toolchain is pulling in latest copies... and this is what the issue was about.

Closing as it's an improvement.

**Comment by realityking** [comment]
@lukeed Note I’m not the maintainer - I just made that PR to get easier access to mine’s patch releases. Ultimately it’s up to @sergcen to decide what he wants to do.

**Comment by lukeed** [comment]
Right :) "you" as in if _you're_ willing to keep opening PRs haha
